apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  labels:
    app: webapp

spec:
  selector:
    app: webapp
  ports:
    - name: httpa
      port: 80
      nodePort: 30080
  type: NodePort
