apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: new-joiner
  namespace: default
rules:
- apiGroups: ["","apps"] # Core API and apiGroups
  resources: ["*"] # pods, services, deployments
  verbs: ["get","list","watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-new-joiner
  namespace: default
subjects:
- kind: User
  name: pandiyan
roleRef:
  kind: Role
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io
