apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: new-joiner
  namespace: default
rules:
- apiGroups: ["","apps"] # Core API and apiGroups
  resources: ["*"] # pods, services, deployments
  verbs: ["get","list","watch"]
