apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  labels:
    app: webapp
    release: "0-5"

spec:
  selector:
    app: webapp
  ports:
    - name: httpa
      port: 80
      nodePort: 30080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  labels:
    app: queue
spec:
  selector:
    app: queue
  ports:
    - name: httpa
      port: 8161
      nodePort: 30010
  type: NodePort
